//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transport_Library
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    [DataContract]
    public partial class Prevozi
    {
        [DataMember]
        public int ID { get; set; }
        [DataMember]
        public int ID_Company { get; set; }
        [DataMember]
        public int StartPoint { get; set; }
        [DataMember]
        public int EndPoint { get; set; }
        [DataMember]
        public System.DateTime Timeof { get; set; }
        [DataMember]
        public byte Freespaces { get; set; }
        [DataMember]
        public Nullable<decimal> Price { get; set; }
    
        public virtual City City { get; set; }
        public virtual City City1 { get; set; }
    }
}
